// ═══════════════════════════════════════════════════════
//  SOLE STORE — products.js
//  ¡EDITA AQUÍ para cambiar nombres y precios!
//  Solo cambia "nombre" y "precio" de cada producto.
// ═══════════════════════════════════════════════════════

export const productosHombre = [
  { id: 1,  img: "imagenes-hombre/zapato1.png",  nombre: "Zapato Deportivo",  precio: "$160.000" },
  { id: 2,  img: "imagenes-hombre/zapato2.png",  nombre: "Tenis Casual",      precio: "$150.000" },
  { id: 3,  img: "imagenes-hombre/zapato3.png",  nombre: "Sneaker Urbano",    precio: "$170.000" },
  { id: 4,  img: "imagenes-hombre/zapato4.png",  nombre: "Running Pro",       precio: "$155.000" },
  { id: 5,  img: "imagenes-hombre/zapato5.png",  nombre: "Clásico Street",    precio: "$145.000" },
  { id: 6,  img: "imagenes-hombre/zapato6.png",  nombre: "Zapato Formal",     precio: "$180.000" },
  { id: 7,  img: "imagenes-hombre/zapato7.png",  nombre: "Bota Urbana",       precio: "$190.000" },
  { id: 8,  img: "imagenes-hombre/zapato8.png",  nombre: "Tenis Low Top",     precio: "$148.000" },
  { id: 9,  img: "imagenes-hombre/zapato9.png",  nombre: "Sneaker Retro",     precio: "$165.000" },
  { id: 10, img: "imagenes-hombre/zapato10.png", nombre: "Sport Elite",       precio: "$175.000" },
  { id: 11, img: "imagenes-hombre/zapato11.png", nombre: "Air Casual",        precio: "$160.000" },
  { id: 12, img: "imagenes-hombre/zapato12.png", nombre: "Urbano Max",        precio: "$158.000" },
  { id: 13, img: "imagenes-hombre/zapato13.png", nombre: "Tenis Street",      precio: "$152.000" },
  { id: 14, img: "imagenes-hombre/zapato14.png", nombre: "Trail Runner",      precio: "$172.000" },
  { id: 15, img: "imagenes-hombre/zapato15.png", nombre: "Classic White",     precio: "$145.000" },
  { id: 16, img: "imagenes-hombre/zapato16.png", nombre: "Bota Táctica",      precio: "$195.000" },
  { id: 17, img: "imagenes-hombre/zapato17.png", nombre: "Sneaker Bold",      precio: "$168.000" },
  { id: 18, img: "imagenes-hombre/zapato18.png", nombre: "Low-Top Clásico",   precio: "$155.000" },
  { id: 19, img: "imagenes-hombre/zapato19.png", nombre: "Sport Lite",        precio: "$162.000" },
  { id: 20, img: "imagenes-hombre/zapato20.png", nombre: "Urban Runner",      precio: "$178.000" },
  { id: 21, img: "imagenes-hombre/zapato21.png", nombre: "Casual Pro",        precio: "$150.000" },
  { id: 22, img: "imagenes-hombre/zapato22.png", nombre: "Tenis Daily",       precio: "$145.000" },
  { id: 23, img: "imagenes-hombre/zapato23.png", nombre: "Sneaker Night",     precio: "$168.000" },
  { id: 24, img: "imagenes-hombre/zapato24.png", nombre: "Bota Ligera",       precio: "$185.000" },
  { id: 25, img: "imagenes-hombre/zapato25.png", nombre: "Running Fast",      precio: "$160.000" },
  { id: 26, img: "imagenes-hombre/zapato26.png", nombre: "Street King",       precio: "$172.000" },
  { id: 27, img: "imagenes-hombre/zapato27.png", nombre: "Casual Look",       precio: "$148.000" },
  { id: 28, img: "imagenes-hombre/zapato28.png", nombre: "Tenis Air",         precio: "$155.000" },
  { id: 29, img: "imagenes-hombre/zapato29.png", nombre: "Retro Urbano",      precio: "$165.000" },
  { id: 30, img: "imagenes-hombre/zapato30.png", nombre: "Sport Max",         precio: "$175.000" },
  { id: 31, img: "imagenes-hombre/zapato31.png", nombre: "Daily Driver",      precio: "$150.000" },
  { id: 32, img: "imagenes-hombre/zapato32.png", nombre: "Tenis Fresh",       precio: "$158.000" },
  { id: 33, img: "imagenes-hombre/zapato33.png", nombre: "Urbano Clásico",    precio: "$145.000" },
  { id: 34, img: "imagenes-hombre/zapato34.png", nombre: "Sneaker Edge",      precio: "$170.000" },
  { id: 35, img: "imagenes-hombre/zapato35.png", nombre: "Boost Casual",      precio: "$162.000" },
  { id: 36, img: "imagenes-hombre/zapato36.png", nombre: "Low Profile",       precio: "$155.000" },
  { id: 37, img: "imagenes-hombre/zapato37.png", nombre: "Tenis Slim",        precio: "$148.000" },
  { id: 38, img: "imagenes-hombre/zapato38.png", nombre: "Street Vibes",      precio: "$165.000" },
  { id: 39, img: "imagenes-hombre/zapato39.png", nombre: "Sport Flex",        precio: "$158.000" },
  { id: 40, img: "imagenes-hombre/zapato40.png", nombre: "Urbano Night",      precio: "$172.000" },
  { id: 41, img: "imagenes-hombre/zapato41.png", nombre: "Classic Run",       precio: "$160.000" },
  { id: 42, img: "imagenes-hombre/zapato42.png", nombre: "Tenis Bold",        precio: "$168.000" },
  { id: 43, img: "imagenes-hombre/zapato43.png", nombre: "Air Street",        precio: "$175.000" },
  { id: 44, img: "imagenes-hombre/zapato44.png", nombre: "Casual Fit",        precio: "$150.000" },
  { id: 45, img: "imagenes-hombre/zapato45.png", nombre: "Sneaker Plus",      precio: "$165.000" },
  { id: 46, img: "imagenes-hombre/zapato46.png", nombre: "Pro Runner",        precio: "$178.000" },
  { id: 47, img: "imagenes-hombre/zapato47.png", nombre: "Tenis Flow",        precio: "$162.000" },
  { id: 48, img: "imagenes-hombre/zapato48.png", nombre: "Urban Edge",        precio: "$155.000" },
  { id: 49, img: "imagenes-hombre/zapato49.png", nombre: "Boost Street",      precio: "$170.000" },
  { id: 50, img: "imagenes-hombre/zapato50.png", nombre: "Classic Fit",       precio: "$148.000" },
  { id: 51, img: "imagenes-hombre/zapato51.png", nombre: "Tenis Sport",       precio: "$158.000" },
  { id: 52, img: "imagenes-hombre/zapato52.png", nombre: "Urban Flex",        precio: "$165.000" },
  { id: 53, img: "imagenes-hombre/zapato53.png", nombre: "Sneaker Drift",     precio: "$172.000" },
  { id: 54, img: "imagenes-hombre/zapato54.png", nombre: "Low Rider",         precio: "$155.000" },
  { id: 55, img: "imagenes-hombre/zapato55.png", nombre: "Street Casual",     precio: "$150.000" },
  { id: 56, img: "imagenes-hombre/zapato56.png", nombre: "Air Max Casual",    precio: "$168.000" },
  { id: 57, img: "imagenes-hombre/zapato57.png", nombre: "Tenis Lite",        precio: "$145.000" },
  { id: 58, img: "imagenes-hombre/zapato58.png", nombre: "Sport Classic",     precio: "$160.000" },
  { id: 59, img: "imagenes-hombre/zapato59.png", nombre: "Urbano Pro",        precio: "$175.000" },
  { id: 60, img: "imagenes-hombre/zapato60.png", nombre: "Runner X",          precio: "$180.000" },
  { id: 61, img: "imagenes-hombre/zapato61.png", nombre: "Tenis Edge",        precio: "$162.000" },
  { id: 62, img: "imagenes-hombre/zapato62.png", nombre: "Boost Elite",       precio: "$178.000" },
  { id: 63, img: "imagenes-hombre/zapato63.png", nombre: "Street Pro",        precio: "$170.000" },
  { id: 64, img: "imagenes-hombre/zapato64.png", nombre: "Casual Step",       precio: "$152.000" },
  { id: 65, img: "imagenes-hombre/zapato65.png", nombre: "Urban Flow",        precio: "$165.000" },
  { id: 66, img: "imagenes-hombre/zapato66.png", nombre: "Sneaker Rush",      precio: "$168.000" },
  { id: 67, img: "imagenes-hombre/zapato67.png", nombre: "Tenis Core",        precio: "$158.000" },
  { id: 68, img: "imagenes-hombre/zapato68.png", nombre: "Classic Urban",     precio: "$155.000" },
  { id: 69, img: "imagenes-hombre/zapato69.png", nombre: "Sport Drive",       precio: "$172.000" },
  { id: 70, img: "imagenes-hombre/zapato70.png", nombre: "Air Flow",          precio: "$165.000" },
  { id: 71, img: "imagenes-hombre/zapato71.png", nombre: "Street Run",        precio: "$160.000" },
  { id: 72, img: "imagenes-hombre/zapato72.png", nombre: "Urbano Edge",       precio: "$168.000" },
  { id: 73, img: "imagenes-hombre/zapato73.png", nombre: "Tenis Plus",        precio: "$155.000" },
  { id: 74, img: "imagenes-hombre/zapato74.png", nombre: "Sneaker Core",      precio: "$175.000" },
  { id: 75, img: "imagenes-hombre/zapato75.png", nombre: "Pro Street",        precio: "$170.000" },
  { id: 76, img: "imagenes-hombre/zapato76.png", nombre: "Boost Run",         precio: "$178.000" },
  { id: 77, img: "imagenes-hombre/zapato77.png", nombre: "Classic Pro",       precio: "$162.000" },
  { id: 78, img: "imagenes-hombre/zapato78.png", nombre: "Urban Max",         precio: "$172.000" },
  { id: 79, img: "imagenes-hombre/zapato79.png", nombre: "Tenis Wave",        precio: "$155.000" },
  { id: 80, img: "imagenes-hombre/zapato80.png", nombre: "Runner Elite",      precio: "$180.000" },
  { id: 81, img: "imagenes-hombre/zapato81.png", nombre: "Street Flow",       precio: "$165.000" },
  { id: 82, img: "imagenes-hombre/zapato82.png", nombre: "Sneaker Ace",       precio: "$168.000" },
  { id: 83, img: "imagenes-hombre/zapato83.png", nombre: "Tenis Boost",       precio: "$162.000" },
  { id: 84, img: "imagenes-hombre/zapato84.png", nombre: "Urban Classic",     precio: "$158.000" },
  { id: 85, img: "imagenes-hombre/zapato85.png", nombre: "Sport Plus",        precio: "$175.000" },
  { id: 86, img: "imagenes-hombre/zapato86.png", nombre: "Air Classic",       precio: "$160.000" },
  { id: 87, img: "imagenes-hombre/zapato87.png", nombre: "Street Bold",       precio: "$170.000" },
  { id: 88, img: "imagenes-hombre/zapato88.png", nombre: "Casual Max",        precio: "$155.000" },
  { id: 89, img: "imagenes-hombre/zapato89.png", nombre: "Tenis Retro",       precio: "$165.000" },
  { id: 90, img: "imagenes-hombre/zapato90.png", nombre: "Urban Run",         precio: "$172.000" },
  { id: 91, img: "imagenes-hombre/zapato91.png", nombre: "Sneaker Flex",      precio: "$168.000" },
  { id: 92, img: "imagenes-hombre/zapato92.png", nombre: "Boost Pro",         precio: "$178.000" },
  { id: 93, img: "imagenes-hombre/zapato93.png", nombre: "Classic Edge",      precio: "$162.000" },
  { id: 94, img: "imagenes-hombre/zapato94.png", nombre: "Sport Wave",        precio: "$175.000" },
  { id: 95, img: "imagenes-hombre/zapato95.png", nombre: "Urban Ace",         precio: "$170.000" },
  { id: 96, img: "imagenes-hombre/zapato96.png", nombre: "Street Elite",      precio: "$180.000" },
];

export const productosMujer = [
  { id: 1,  img: "imagenes-mujer/zapato1.png",  nombre: "Ballet Clásico",    precio: "$120.000" },
  { id: 2,  img: "imagenes-mujer/zapato2.png",  nombre: "Sneaker Pastel",    precio: "$135.000" },
  { id: 3,  img: "imagenes-mujer/zapato3.png",  nombre: "Casual Chic",       precio: "$128.000" },
  { id: 4,  img: "imagenes-mujer/zapato4.png",  nombre: "Platform Style",    precio: "$145.000" },
  { id: 5,  img: "imagenes-mujer/zapato5.png",  nombre: "Street Femme",      precio: "$138.000" },
  { id: 6,  img: "imagenes-mujer/zapato6.png",  nombre: "Tenis Soft",        precio: "$125.000" },
  { id: 7,  img: "imagenes-mujer/zapato7.png",  nombre: "Urbana Chic",       precio: "$142.000" },
  { id: 8,  img: "imagenes-mujer/zapato8.png",  nombre: "Runner Rosa",       precio: "$130.000" },
  { id: 9,  img: "imagenes-mujer/zapato9.png",  nombre: "Classic Femme",     precio: "$122.000" },
  { id: 10, img: "imagenes-mujer/zapato10.png", nombre: "Sneaker Glam",      precio: "$140.000" },
  { id: 11, img: "imagenes-mujer/zapato11.png", nombre: "Casual Bloom",      precio: "$128.000" },
  { id: 12, img: "imagenes-mujer/zapato12.png", nombre: "Sport Femme",       precio: "$135.000" },
  { id: 13, img: "imagenes-mujer/zapato13.png", nombre: "Low Cut Chic",      precio: "$125.000" },
  { id: 14, img: "imagenes-mujer/zapato14.png", nombre: "Urbana Flow",       precio: "$138.000" },
  { id: 15, img: "imagenes-mujer/zapato15.png", nombre: "Tenis Dream",       precio: "$132.000" },
  { id: 16, img: "imagenes-mujer/zapato16.png", nombre: "Pastel Street",     precio: "$128.000" },
  { id: 17, img: "imagenes-mujer/zapato17.png", nombre: "Sneaker Vibe",      precio: "$140.000" },
  { id: 18, img: "imagenes-mujer/zapato18.png", nombre: "Casual Soft",       precio: "$122.000" },
  { id: 19, img: "imagenes-mujer/zapato19.png", nombre: "Runner Chic",       precio: "$135.000" },
  { id: 20, img: "imagenes-mujer/zapato20.png", nombre: "Urban Femme",       precio: "$142.000" },
  { id: 21, img: "imagenes-mujer/zapato21.png", nombre: "Classic Style",     precio: "$125.000" },
  { id: 22, img: "imagenes-mujer/zapato22.png", nombre: "Tenis Glow",        precio: "$138.000" },
  { id: 23, img: "imagenes-mujer/zapato23.png", nombre: "Street Glam",       precio: "$132.000" },
  { id: 24, img: "imagenes-mujer/zapato24.png", nombre: "Sneaker Bloom",     precio: "$128.000" },
  { id: 25, img: "imagenes-mujer/zapato25.png", nombre: "Casual Vibe",       precio: "$135.000" },
  { id: 26, img: "imagenes-mujer/zapato26.png", nombre: "Urban Dream",       precio: "$140.000" },
  { id: 27, img: "imagenes-mujer/zapato27.png", nombre: "Tenis Soft Flow",   precio: "$130.000" },
  { id: 28, img: "imagenes-mujer/zapato28.png", nombre: "Classic Glow",      precio: "$125.000" },
  { id: 29, img: "imagenes-mujer/zapato29.png", nombre: "Runner Femme",      precio: "$138.000" },
  { id: 30, img: "imagenes-mujer/zapato30.png", nombre: "Pastel Chic",       precio: "$128.000" },
  { id: 31, img: "imagenes-mujer/zapato31.png", nombre: "Sneaker Pastel Pro", precio: "$142.000" },
  { id: 32, img: "imagenes-mujer/zapato32.png", nombre: "Urbana Style",      precio: "$135.000" },
  { id: 33, img: "imagenes-mujer/zapato33.png", nombre: "Casual Glam",       precio: "$130.000" },
  { id: 34, img: "imagenes-mujer/zapato34.png", nombre: "Tenis Bloom",       precio: "$125.000" },
  { id: 35, img: "imagenes-mujer/zapato35.png", nombre: "Street Dream",      precio: "$138.000" },
  { id: 36, img: "imagenes-mujer/zapato36.png", nombre: "Runner Glow",       precio: "$140.000" },
  { id: 37, img: "imagenes-mujer/zapato37.png", nombre: "Urban Vibe",        precio: "$145.000" },
  { id: 38, img: "imagenes-mujer/zapato38.png", nombre: "Classic Femme Pro", precio: "$135.000" },
  { id: 39, img: "imagenes-mujer/zapato39.png", nombre: "Sneaker Style",     precio: "$132.000" },
  { id: 40, img: "imagenes-mujer/zapato40.png", nombre: "Casual Dream",      precio: "$128.000" },
  { id: 41, img: "imagenes-mujer/zapato41.png", nombre: "Tenis Chic Pro",    precio: "$140.000" },
];